### ISSUE TITLE
类似断点续传的功能

### ISSUE THREAD

**Issue by liuxiangteng** [panpf/sketch#101]
你好  请教一下  我现在遇到的问题是  我打开一个界面去查看原图的时候  会初始化SketchImageView  比如这个图片较大 网速又不好  我加载到百分之三十的时候  就退出查看界面了   然后我再想看的时候 就又从头开始加载了    这个可以怎么优化一下吗？

**Comment by panpf** [comment]
确实没有做断点续传的功能，当时主要考虑到断点续传不利于自动回收过期文件所以就没做
另外你的 app 中会有很多这种大图片吗？需求很强烈吗？

**Comment by liuxiangteng** [comment]
因为有社区的功能，用户都在社区发图，自己今天吃了啥都发，图很多，为了节省流量，列表里都是缩略图的链接，点击查看的时候才是原图，这样图片大网速不好的时间就会出来的比较慢，然后用户等了几秒就退出加载图片的界面，等再点开进入的时候又是从0开始加载了，就是因为考虑了这个问题 才跟您提了一下。
