### ISSUE TITLE
希望支持播放raw文件夹下资源

### ISSUE THREAD

**Issue by lizhiwei92** [panpf/sketch#104]
希望支持播放raw文件夹下资源

**Comment by panpf** [comment]
"drawable://"+R.raw.image 作为 uri 就可以支持

**Comment by lizhiwei92** [comment]
![image](https://user-images.githubusercontent.com/22723524/56705841-3f111800-6745-11e9-84c0-21c6b05999fa.png)

大佬，加个注解吧

![image](https://user-images.githubusercontent.com/22723524/56705872-5c45e680-6745-11e9-9bd8-5318a548331c.png)
