### ISSUE TITLE
显示gif时，只播放了一遍，没有循环

### ISSUE THREAD

**Issue by lizhiwei92** [panpf/sketch#105]
加载gif时，只播放了一遍，没有循环播放
        sketchGif.getOptions().setDecodeGifImage(true);
        sketchGif.displayResourceImage(R.drawable.magic_ball2);

**Comment by panpf** [comment]
默认就是循环播放的，你换图试试

**Comment by lizhiwei92** [comment]
换了一张gif，是循环播了。问了一下UI，UI说他们可以选择导出播放一次或者循环播放的文件，涨见识了。

**Comment by panpf** [comment]
世界之大，无奇不有！永保敬畏之心！
