### ISSUE TITLE
网络图片无法加载请大神分析下原因

### ISSUE THREAD

**Issue by yangyang9** [panpf/sketch#108]
glide 可以加载该图片,我抓包检查响应头content-length也有数据,但是断点代码显示content-length为0   
图片地址为:http://img1.easypass.cn/das/carsource1/origin/50a9d24a-3535-4833-947e-64a75234e149.png
![企业微信截图_bd78715a-30c9-45ea-a9af-0f47f423fd4f](https://user-images.githubusercontent.com/29140559/57495643-bcba5380-7301-11e9-83b3-d4b72aab7384.png)

**Comment by panpf** [comment]
在手机浏览器里试试

**Comment by yangyang9** [comment]
> 在手机浏览器里试试
试了,手机浏览器能打开

**Comment by panpf** [comment]
昨天发了新版 2.7.1 beta 1 更新试试

**Comment by yangyang9** [comment]
好的我试试
