### ISSUE TITLE
感觉过于庞大与复杂，想与glide 配合使用，不知道怎么操作？

### ISSUE THREAD

**Issue by zomll** [panpf/sketch#109]
如题

**Comment by panpf** [comment]
为什要跟 glide 配合使用，不建议这样做，图片加载框架都会申请固定的内存缓存，同时使用多个的话会同时申请多份内存缓存，导致 App 可用内存降低

**Comment by zomll** [comment]
> 为什要跟 glide 配合使用，不建议这样做，图片加载框架都会申请固定的内存缓存，同时使用多个的话会同时申请多份内存缓存，导致 App 可用内存降低

主要是先有项目已经开发很久了，里面图片加载都是用的glide，全部替换为sketch 不太方便

**Comment by panpf** [comment]
这种情况确实不太好替换，如果不是非换不可，还是保持现状，具体还得看需求

**Comment by zhuangzhitu** [comment]
+1。代码设计有点复杂，有些人可能只想用大图加载以及缩放功能，发现不好抽离代码。

**Comment by panpf** [comment]
全新 3.0 版本已经发布 alpha 版，欢迎体验。任意 ImageView 都可以
