### ISSUE TITLE
支持cookie吗

### ISSUE THREAD

**Issue by muziling** [panpf/sketch#110]
比如论坛的图片，登录后才能看， 图片设置http地址的时候，能设置cookie吗？

**Comment by panpf** [comment]
暂不支持，个别需求你可以自定义 HttpStack 实现

**Comment by muziling** [comment]
最终在HurlStack的 getResponse 里加了 
connection.setRequestProperty("Cookie", CookieManager.getInstance().getCookie(uri));
搞定。希望能默认或设置为configuration的开关

**Comment by panpf** [comment]
列入下版本计划
