### ISSUE TITLE
recycleview里gif的播放图标点不了

### ISSUE THREAD

**Issue by muziling** [panpf/sketch#111]
看了demo，demo里没有用recycleview，
我的代码里用了recycleview，代码里设置了这几个属性
                iv_post_image.isShowDownloadProgressEnabled = true
                iv_post_image.isClickRetryOnDisplayErrorEnabled = true
                iv_post_image.options.setErrorImage(R.drawable.ic_error)
                iv_post_image.setShowGifFlagEnabled(R.drawable.ic_gif)
                iv_post_image.setClickPlayGifEnabled(R.drawable.ic_video_play)
                iv_post_image.displayImage(res.second.toString())
然后GIF图加载完成后，播放图标点了没反应，滚动recycleview，让这个图不在屏幕中，再滚动回来显示，这时播放图标点了才有反应。

**Comment by panpf** [comment]
好的，我试试

**Comment by muziling** [comment]
recycleview 里的textview 有时选不中，按
https://blog.csdn.net/suyimin2010/article/details/85914896 这里说的设置一下就可以了。
但 iv_post_image 类似设置不行，不知道是哪里的问题。
