### ISSUE TITLE
缩放体验不好

### ISSUE THREAD

**Issue by fltwlulu** [panpf/sketch#112]
在ViewPager里面使用

1。双击然后手指不松开拖动手指可以继续缩放，但是双击后尽管手指没有松开，然而图片立刻就进入最大的放大状态。

2。双击放大后可见的是图片的右下角而不是手指点击的位置或图片中心。

3。有的GIF播放不了

**Comment by panpf** [comment]
单独的 zoomimage （ https://github.com/panpf/zoomimage ）库来了，支持 compose 和 view，两个版本逻辑和体验完全一致

新的 zoomimage 库在 sketch-zoom 的基础上完全重构，用户体验全面提升，除修复了一些 bug 之外还新支持了子采样碎片的动画和清晰度渐变以及支持 glide、picasso、coil、等图片加载器

目前已经到了公开测试的 beta 阶段，欢迎到 [release](https://github.com/panpf/zoomimage/releases) 页面下载 APK 体验效果

sketch-zoom 模块以后将不再提供更新
