### ISSUE TITLE
最新版本部分图片显示不出来

### ISSUE THREAD

**Issue by liuxiangteng** [panpf/sketch#114]
你好，最新版本（2.7.1-beta1）出现一些动图加载了但是不显示的情况   还原到2.7.0就没有这种情况

**Comment by panpf** [comment]
是的，最新版本加了 content-type 限制，显示不出来的 content-type 肯定不是 image/* logcat 中会有错误提示，这个只是 beta 版本不要用到生产环境中，后续会改一下

**Comment by liuxiangteng** [comment]
OK
