### ISSUE TITLE
sketchview如何加载证书加密的https图片

### ISSUE THREAD

**Issue by luojialun** [panpf/sketch#117]
项目中之前使用gilde加载图片的，也做好了证书校验，但是sketchview没找到相关的加载证书加密图片的方法，请指教

**Comment by panpf** [comment]
这种特殊的需求，需要自定义 Http 部分实现，请参考链接 https://github.com/panpf/sketch/blob/master/docs/wiki/http_stack.md

**Comment by luojialun** [comment]
> 这种特殊的需求，需要自定义 Http 部分实现，请参考链接 https://github.com/panpf/sketch/blob/master/docs/wiki/http_stack.md

该如何设置证书校验呢，提供的方法里没有像SocketFactory这样相关的方法

**Comment by panpf** [comment]
没有的，你参考 glide 的写一个吧
