### ISSUE TITLE
希望能开放接口自定义showDownloadProgressFunction

### ISSUE THREAD

**Issue by muziling** [panpf/sketch#118]
源代码为：getFunctions().showDownloadProgressFunction = new ShowDownloadProgressFunction(this);
希望能开放接口 ，自定义一个 ShowDownloadProgressFunction，比如名字为 MyShowDownloadProgressFunction，然后 设置到 getFunctions().showDownloadProgressFunction

目的是我想要重写ShowDownloadProgressFunction里的onDraw函数，
用https://github.com/abdularis/AndroidButtonProgress 这里面的 canvas 重绘，进度条比自带的蒙板效果更好看

**Comment by panpf** [comment]
全新 3.0 版本已经发布 alpha 版，欢迎体验。可以自定义进度
