### ISSUE TITLE
diskCache.exist(url)第一次打开图片一直返回的是true

### ISSUE THREAD

**Issue by xxxxxxH** [panpf/sketch#121]
diskCache.exist(url)第一次打开图片一直返回的是true  
第一次新打开图片 一直反回true 请问是什么情况呢

**Comment by panpf** [comment]
如果 exist 方法出错的话网络图片一张都显示不了。你可以到 /sdcard/android/data/[app]/cache/sketch 目录下找一下是否有这个 url 的缓存文件，缓存文件名是 url 的 MD5 结果

**Comment by xxxxxxH** [comment]
我知道问题出在哪儿了 蟹蟹大佬百忙之中解惑
