### ISSUE TITLE
有的图片显示模糊，估计使用RGB_565的原因，怎么自己设置用ARGB_8888显示呢？

### ISSUE THREAD

**Issue by WarriorYu** [panpf/sketch#122]

**Comment by WarriorYu** [comment]
这是代码，倒数第三行设置了(Bitmap.Config.ARGB_8888)，不放大显示正常，放大后就像使用了RGB_565显示模糊,着急实现这个功能，麻烦回复一下，谢谢了。另外可以加你微信吗？
        img.setZoomEnabled(true);
        img.getZoomer().getBlockDisplayer().setPause(true);
        // 批量配置显示属性
        DisplayOptions displayOptions = new DisplayOptions();
        displayOptions.setBitmapConfig(Bitmap.Config.ARGB_8888);
        img.setOptions(displayOptions);
        img.displayImage(url);

**Comment by panpf** [comment]
进 QQ 群细聊吧
