### ISSUE TITLE
缩放和占位图问题

### ISSUE THREAD

**Issue by FrankLove** [panpf/sketch#124]
1、整个页面只有一个imageview,如果在xml里面设置宽高为wrap,那么缩放的时候只能在一个固定区域内缩放，无法在整个页面缩放。设置占位图可以按实际大小显示
2、整个页面只有一个imageview,如果在xml里面设置宽高为math，那么可以缩放区域可以伸缩到整个页面，但是设置的占位图没有按实际大小显示

**Comment by panpf** [comment]
抱歉我不太明白你的需求，能否画图或有贴一个示例截图

**Comment by FrankLove** [comment]
不好意思，可能是我没表达清楚，主要是两个问题占位图和缩放
情况是这样的
1、如果将imageview设置成铺满全屏，那么占位图显示的时候就无法按照实际尺寸显示，所以想按照实际尺寸显示占位图就必须把imageview设置成wrap_content，但是如果设置成这样，对图片进行缩放的时候就会出现不能全屏缩放，会出现在一个固定区域内缩放。
这样说不知是否表达清楚了
@panpf

**Comment by panpf** [comment]
你 ScaleType 是不是设置了 FIT_XY

**Comment by FrankLove** [comment]
@panpf 没有设置

**Comment by panpf** [comment]
进群聊吧，这样有点儿费劲

**Comment by laiforever3** [comment]
同样的问题，怎么处理

**Comment by laiforever3** [comment]
@panpf

**Comment by FrankLove** [comment]
@laiforever3 
    <me.panpf.sketch.SketchImageView
        android:id="@+id/iv_frag_image"
        android:layout_width="0dp"
        android:layout_height="0dp"
        android:scaleType="centerInside"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        />

**Comment by laiforever3** [comment]
> <me.panpf.sketch.SketchImageView
> android:id="@+id/iv_frag_image"
> android:layout_width="0dp"
> android:layout_height="0dp"
> android:scaleType="centerInside"
> app:layout_constraintBottom_toBottomOf="parent"
> app:layout_constraintEnd_toEndOf="parent"
> app:layout_constraintStart_toStartOf="parent"
> app:layout_constraintTop_toTopOf="parent"
> />
这样如果图片宽高没有达到屏幕的大小。不会放大到全屏

**Comment by FrankLove** [comment]
@laiforever3 会的
