### ISSUE TITLE
请问一下我是在recyleview中的adapter里用到了这个库，用来做图片查看预览大图画廊

### ISSUE THREAD

**Issue by dary123** [panpf/sketch#130]
但是遇到了一个问题，我需要在recyleview或者包含的item点击整块区域时，顶部bar要缩回去，如果使用了photo_view.setZoomEnabled(true);photo_view.getZoomer().setReadMode(true);就没法监听到点击事件，因为被拦截了，如果去掉这两行代码才可以，如何解决这个冲突问题

**Comment by panpf** [comment]
我不会在列表中开启手势缩放，我也没有考虑在列表中手势缩放的问题，你为什么非要在列表中开启手势缩放

**Comment by dary123** [comment]
因为要做左右滑动查看图片啊

**Comment by panpf** [comment]
是用 RecyclerView 代替 ViewPager 吗？

**Comment by panpf** [comment]
直接在 photo_view 上调用 setOnClickListener 即可拿到点击事件
