### ISSUE TITLE
双击放大后才清晰 未放大是模糊的

### ISSUE THREAD

**Issue by dary123** [panpf/sketch#131]
双击放大后才清晰 未放大是模糊的

**Comment by kekegdsz** [comment]
+1

**Comment by panpf** [comment]
全新 3.0 版本已经发布 alpha 版，欢迎体验。新版本默认很清晰

**Comment by panpf** [comment]
单独的 zoomimage （ https://github.com/panpf/zoomimage ）库来了，支持 compose 和 view，两个版本逻辑和体验完全一致

新的 zoomimage 库在 sketch-zoom 的基础上完全重构，用户体验全面提升，除修复了一些 bug 之外还新支持了子采样碎片的动画和清晰度渐变以及支持 glide、picasso、coil、等图片加载器

目前已经到了公开测试的 beta 阶段，欢迎到 [release](https://github.com/panpf/zoomimage/releases) 页面下载 APK 体验效果

sketch-zoom 模块以后将不再提供更新
