### ISSUE TITLE
图片默认填充屏幕

### ISSUE THREAD

**Issue by WiseDiligent** [panpf/sketch#137]
图片尺寸的大小，本来是占满屏幕的，有方法可以在继续支持放大吗，现在一放大就回弹。。。

**Comment by WiseDiligent** [comment]
能不能支持无限放大，或者可以设置放大到一定的范围

**Comment by panpf** [comment]
全新 3.0 版本已经发布 alpha 版，欢迎体验。新版本在之前最大的基础上还能继续放大

**Comment by panpf** [comment]
单独的 zoomimage （ https://github.com/panpf/zoomimage ）库来了，支持 compose 和 view，两个版本逻辑和体验完全一致

新的 zoomimage 库在 sketch-zoom 的基础上完全重构，用户体验全面提升，除修复了一些 bug 之外还新支持了子采样碎片的动画和清晰度渐变以及支持 glide、picasso、coil、等图片加载器

目前已经到了公开测试的 beta 阶段，欢迎到 [release](https://github.com/panpf/zoomimage/releases) 页面下载 APK 体验效果

sketch-zoom 模块以后将不再提供更新
