### ISSUE TITLE
Tablayout+Viewpager+Fragment+gif+卡顿

### ISSUE THREAD

**Issue by 240651388** [panpf/sketch#138]
Tablayout+Viewpager的6个fragment，都展示图片列表【服务器返回图片含png、gif，比例7:3】，gif默认设置自动播放，请问切换fragment时，是否需要通知即将不可见的fragment的列表停止播放gif呢？有其他setting或者方法可以减轻卡顿的吗？【gif来自服务器，平均大小600K+】

**Comment by panpf** [comment]
停止播放是必须的，你可以减少图片数量减少内存占用来减轻卡顿
