### ISSUE TITLE
放大超出边界会缩放回去

### ISSUE THREAD

**Issue by conghuahuadan** [panpf/sketch#139]
你好，作者，如果不断放大超出边界，会缩放回去，这个功能可以禁止吗

**Comment by panpf** [comment]
暂时不可以

**Comment by conghuahuadan** [comment]
我找一个方法了


public class DefaultScales extends AdaptiveTwoLevelScales {

    @Override
    public float getMaxZoomScale() {
        return Float.MAX_VALUE;
    }
}

**Comment by panpf** [comment]
单独的 zoomimage （ https://github.com/panpf/zoomimage ）库来了，支持 compose 和 view，两个版本逻辑和体验完全一致

新的 zoomimage 库在 sketch-zoom 的基础上完全重构，用户体验全面提升，除修复了一些 bug 之外还新支持了子采样碎片的动画和清晰度渐变以及支持 glide、picasso、coil、等图片加载器

目前已经到了公开测试的 beta 阶段，欢迎到 [release](https://github.com/panpf/zoomimage/releases) 页面下载 APK 体验效果

sketch-zoom 模块以后将不再提供更新
