### ISSUE TITLE
图片放大缩小有时候会空指针啊

### ISSUE THREAD

**Issue by xuxinjiang** [panpf/sketch#142]

**Comment by panpf** [comment]
反馈 bug 请附上 sketch 版本，android 版本，图片 url，设备型号，异常栈等信息方便排查，谢谢！

**Comment by panpf** [comment]
单独的 zoomimage （ https://github.com/panpf/zoomimage ）库来了，支持 compose 和 view，两个版本逻辑和体验完全一致

新的 zoomimage 库在 sketch-zoom 的基础上完全重构，用户体验全面提升，除修复了一些 bug 之外还新支持了子采样碎片的动画和清晰度渐变以及支持 glide、picasso、coil、等图片加载器

目前已经到了公开测试的 beta 阶段，欢迎到 [release](https://github.com/panpf/zoomimage/releases) 页面下载 APK 体验效果

sketch-zoom 模块以后将不再提供更新
