### ISSUE TITLE
图片放大后出现模糊，需要一段时间才显示清晰

### ISSUE THREAD

**Issue by WeicongLi124** [panpf/sketch#143]
在性能较好的机器上显示会比较快，但是性能较差的机器需要较长时间才能将图片显示清晰，请问这个有优化的方案吗？

**Comment by panpf** [comment]
暂时没有，后续可能要加多线程优化

**Comment by WeicongLi124** [comment]
了解，谢谢。

**Comment by william-lw** [comment]
作者是否有优化计划？

**Comment by panpf** [comment]
全新 3.0 版本已经发布 alpha 版，欢迎体验。现在支持多线程，速度快了很多

**Comment by WeicongLi124** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
