### ISSUE TITLE
ImageRegionDecodeThread4  SIGSEGV(SEGV_MAPERR)

### ISSUE THREAD

**Issue by PangHaHa12138** [panpf/sketch#146]
1 #00 pc 000311bc /system/lib/libjpeg-alpha.so [armeabi-v8]
--
2 java:
3 android.graphics.BitmapRegionDecoder.decodeRegion(BitmapRegionDecoder.java:194)
4 com.wodi.sdk.photopreview.previewlibrary.sketch.core.zoom.block.ImageRegionDecoder.a(ImageRegionDecoder.java:142)
5 com.wodi.sdk.photopreview.previewlibrary.sketch.core.zoom.block.DecodeHandler.a(DecodeHandler.java:136)
6 com.wodi.sdk.photopreview.previewlibrary.sketch.core.zoom.block.DecodeHandler.handleMessage(DecodeHandler.java:78)
7 android.os.Handler.dispatchMessage(Handler.java:106)
8 android.os.Looper.loop(Looper.java:224)
9 android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by PangHaHa12138** [comment]
这是bugly上崩溃的信息，没有修改sketch源码，直接copy源码使用的

**Comment by panpf** [comment]
看样子是设备的系统源码的 bug

**Comment by panpf** [comment]
单独的 zoomimage （ https://github.com/panpf/zoomimage ）库来了，支持 compose 和 view，两个版本逻辑和体验完全一致

新的 zoomimage 库在 sketch-zoom 的基础上完全重构，用户体验全面提升，除修复了一些 bug 之外还新支持了子采样碎片的动画和清晰度渐变以及支持 glide、picasso、coil、等图片加载器

目前已经到了公开测试的 beta 阶段，欢迎到 [release](https://github.com/panpf/zoomimage/releases) 页面下载 APK 体验效果

sketch-zoom 模块以后将不再提供更新
