### ISSUE TITLE
图片打开模糊，需要移动一下才清晰，否者一直模糊

### ISSUE THREAD

**Issue by kekegdsz** [panpf/sketch#147]

**Comment by kekegdsz** [comment]
是否有关闭局部加载功能

**Comment by kekegdsz** [comment]
关闭支持局部加载还是模糊

**Comment by kekegdsz** [comment]
![image](https://user-images.githubusercontent.com/17893790/120196793-d87b5400-c252-11eb-851d-65010955270a.png)
把这里注释的就可以了

**Comment by panpf** [comment]
全新 3.0 版本已经发布 alpha 版，欢迎体验。大图打开默认是清晰的

**Comment by panpf** [comment]
单独的 zoomimage （ https://github.com/panpf/zoomimage ）库来了，支持 compose 和 view，两个版本逻辑和体验完全一致

新的 zoomimage 库在 sketch-zoom 的基础上完全重构，用户体验全面提升，除修复了一些 bug 之外还新支持了子采样碎片的动画和清晰度渐变以及支持 glide、picasso、coil、等图片加载器

目前已经到了公开测试的 beta 阶段，欢迎到 [release](https://github.com/panpf/zoomimage/releases) 页面下载 APK 体验效果

sketch-zoom 模块以后将不再提供更新
