### ISSUE TITLE
只是加载一张大图，而不开启手势缩放该怎么做

### ISSUE THREAD

**Issue by yangqb** [panpf/sketch#150]

**Comment by panpf** [comment]
就把大图当普通图片加载就可以了，手势缩放默认是关闭的

**Comment by yangqb** [comment]
我是想让一张图片按原尺寸加载出来4000*6000的，实际加载出来的好像进行了缩放了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月14日(周六) 晚上10:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [panpf/sketch] 只是加载一张大图，而不开启手势缩放该怎么做 (#150)




 
就把大图当普通图片加载就可以了，手势缩放默认是关闭的
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by panpf** [comment]
这不是手势缩放导致的，这是默认的 maxSize 限制的，你把 maxSize 调大一些就行了

**Comment by yangqb** [comment]
> 这不是手势缩放导致的，这是默认的 maxSize 限制的，你把 maxSize 调大一些就行了

是的，昨天已经处理好了
