### ISSUE TITLE
android-gif-drawable 

### ISSUE THREAD

**Issue by lh1241698502** [panpf/sketch#154]
会考虑升级下android-gif-drawable 的版本吗

**Comment by lh1241698502** [comment]
这个集成方式能不能改为implementation，我项目里的其他模块单独用到了gif_drawable，会有冲突报错：Duplicate class
![Uploading WechatIMG149.png…]()

**Comment by panpf** [comment]
目前还不行，因为有修改。新的 3.0 版本将会是 implementation 的

**Comment by lh1241698502** [comment]
> 目前还不行，因为有修改。新的 3.0 版本将会是 implementation 的

期待新版本

**Comment by panpf** [comment]
全新版本已经发布 alpha 版本，欢迎体验
