### ISSUE TITLE
me.panpf:sketch-gif:2.7.1 也是作者的么

### ISSUE THREAD

**Issue by Wan7451** [panpf/sketch#155]
me.panpf:sketch-gif:2.7.1   这个库可是作者的么？
和现在的 io.github.panpf.sketch:sketch-gif:2.7.1 有啥区别么

**Comment by panpf** [comment]
没有区别，只是 maven group id 变了

**Comment by Wan7451** [comment]
so文件 在源库的基础上有改动么

**Comment by panpf** [comment]
没有

**Comment by panpf** [comment]
全新 3.0 版本已经发布 alpha 版，欢迎体验
