### ISSUE TITLE
为什么SVG缩放后会变模糊？

### ISSUE THREAD

**Issue by XuMengren** [panpf/sketch#157]

**Comment by panpf** [comment]
请补充更多信息，使用场景，使用环境，版本等

**Comment by XuMengren** [comment]
渲染CAD模型，缩放后线条和文字变的非常模糊，版本用的最新版

**Comment by panpf** [comment]
sketch 是用的 https://github.com/BigBadaboom/androidsvg 库将 svg 转为 Bitmap 的，你可以先试下这个库看看是哪里的问题，

实在不行可以换成别的库或者参考文档 https://github.com/panpf/sketch/blob/main/docs/wiki/decoder.md 自定义一个 BitmapDecoder
