### ISSUE TITLE
双指缩放后单指抬起问题

### ISSUE THREAD

**Issue by ThankRain** [panpf/sketch#160]
双指放大后抬起一个手指会导致中心点跑到剩下的那个手指那去，图片就会瞬间平移闪烁一下

**Comment by panpf** [comment]
好的，体验相关问题还在持续优化中，敬请期待

**Comment by panpf** [comment]
单独的 zoomimage （ https://github.com/panpf/zoomimage ）库来了，支持 compose 和 view，两个版本逻辑和体验完全一致

新的 zoomimage 库在 sketch-zoom 的基础上完全重构，用户体验全面提升，除修复了一些 bug 之外还新支持了子采样碎片的动画和清晰度渐变以及支持 glide、picasso、coil、等图片加载器

目前已经到了公开测试的 beta 阶段，欢迎到 [release](https://github.com/panpf/zoomimage/releases) 页面下载 APK 体验效果

你提到的这个问题也在 zoomimage 中修复了
