### ISSUE TITLE
Gravity of zoomable images

### ISSUE THREAD

**Issue by saket** [panpf/sketch#162]
When an image is zoomed, `SketchZoomImageView`'s current behavior is to scale on all sides which makes sense for most image viewer apps where the image is displayed at the center. Will it be possible to customize this behavior by taking in a "gravity"? I am trying to display an image at the top of the screen. If the image is zoomed, I'd like it to scale up towards the bottom edge of the image until it reaches its maximum height.

**Comment by panpf** [comment]
I can't imagine such a usage scenario, please describe in more detail why there is such a requirement displayed at the top

**Comment by saket** [comment]
I have a screen that shows an image as its header. The image can be zoomed, but its height remains fixed.

**Comment by saket** [comment]
Closing in favor of [telephoto](https://saket.github.io/telephoto/).
