### ISSUE TITLE
#Sketch: ImageDecoder. Decode failed

### ISSUE THREAD

**Issue by HehuanAndroid** [panpf/sketch#163]
#Sketch: ImageDecoder. Decode failed

why Image width or height less than or equal to 1px

**Comment by panpf** [comment]
可能有以下几种原因：
1. 图片下载不完整
2. http url 链接失效返回的内容不是图片
3. 图片格式不支持

注意看看是哪些图片有这样的问题，是偶尔的还是可稳定复现的，找找特征

**Comment by HehuanAndroid** [comment]
偶尔会出现  没规律 不好复现  url地址也没有问题  我试过第一次出现这个bug  我再次加载然后任然可以显示出图片了

**Comment by HehuanAndroid** [comment]
> 可能有以下几种原因：
> 
> 1. 图片下载不完整
> 2. http url 链接失效返回的内容不是图片
> 3. 图片格式不支持
> 
> 注意看看是哪些图片有这样的问题，是偶尔的还是可稳定复现的，找找特征

如果我想要设置图片放大不受高度限制要怎么设置

**Comment by panpf** [comment]
如果是 heif 或 heic 图片就不奇怪了，我也遇到过，暂不清楚是何原因

**Comment by panpf** [comment]
如果我想要设置图片放大不受高度限制要怎么设置？

不是很明白你的意思

**Comment by HehuanAndroid** [comment]
> 

   缩放倍数不是会变化的吗         它不是去测量了图片的宽高来决定缩放的倍数吗

**Comment by panpf** [comment]
你说的是 zoom 功能的双击缩放倍数吗？如果是的话可以自定义 ScalesFactory 达到此目的，可以参考 ScalesFactory 的现有实现
