### ISSUE TITLE
2.7.1升级 api 改动问题

### ISSUE THREAD

**Issue by yangdong123** [panpf/sketch#164]
2.7.1升级 到最新版本部分api 没有了

**Comment by panpf** [comment]
3.几版本完全重构了，当一个新的库用就行了，需要视情况和成本决定是否升级

**Comment by yangdong123** [comment]
导入库 类找不到 SpiderMan: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/github/panpf/sketch/target/ImageViewDisplayTarget;

**Comment by panpf** [comment]
Sketch 能找到吗？ImageViewDisplayTarget 跟 Sketch 是同一个包的，如果 Sketch 找的到可能是别的原因，需要你自己解决。如果都找不到你看看是不是依赖没有导入成功
