### ISSUE TITLE
how to get the real pixel xy

### ISSUE THREAD

**Issue by dekacaishui** [panpf/sketch#165]
Hi, I would like to draw a cross on sketch zoom view, I use getMatrix() function to get the matrix and calculate the new xy after zoom in or zoom out, but failed, could anyone help me that how to get the real pixel xy and how to get the correct matrix to calculate the xy after zoom?
![capture](https://user-images.githubusercontent.com/51400464/189465537-8f2940b6-3267-48fe-a76e-bc282a175a64.PNG)

**Comment by panpf** [comment]
你只需要 先 ‘canvas.concat(matrix)’ 然后再正常绘制你的十字星即可
