### ISSUE TITLE
[feature] 能否在HttpStack的getResponse()方法中增加suspend关键字

### ISSUE THREAD

**Issue by Raven-L** [panpf/sketch#167]
看了源码发现getResponse()实际上也是在协程中执行，增加suspend应该没有大的影响。
而对于某些http框架如：Ktor，其不支持使用同步方式进行请求。所以希望为getResponse()增加suspend，扩展性会更好一些。

**Comment by panpf** [comment]
下个版本可以加上

**Comment by panpf** [comment]
新版本加了 suspend 关键字了，可以试试了
