### ISSUE TITLE
SketchImageView支持在使用Databinding的xml布局里面加载model里面的网络图片吗

### ISSUE THREAD

**Issue by MiChongs** [panpf/sketch#170]

**Comment by panpf** [comment]
目前不支持，并且也没有支持的计划。因为 DataBinding 应用范围不广，它只是一个过渡性的技术方案，现在有了 compose 它只会越来越没人用

如果你的项目中用到了你可以继承 SketchImageView 然后给它增加一个支持 DataBinding 的自定义属性，让这个属性最终调用 displayImage 方法，具体如何自定义支持 DataBinding 的属性请参考这篇文章 
 https://blog.csdn.net/lckj686/article/details/104767394
