### ISSUE TITLE
SketchZoomImageView 在 Compose 中调用时出现滑动事件问题

### ISSUE THREAD

**Issue by HuanCheng65** [panpf/sketch#171]
在 Compose 界面中使用 AndroidView 调用 SketchZoomImageView，会导致 Pager 中滑动没有反应

**Comment by panpf** [comment]
这个操作我确实还没有试过，待我试试先

**Comment by panpf** [comment]
这个问题暂时无法解决，貌似是 Compose 版 Pager的 bug
首先，SketchZoomImageView 正确调用了 requestDisallowInterceptTouchEvent 方法，AndroidView 也接收了
其次，SketchZoomImageView 也正确的实现了 canScrollHorizontally 和 canScrollVertically 方法
另外，我也拿 WebView 替代 SketchZoomImageView 试了一下，同样无法左右滑动切换 page

**Comment by HuanCheng65** [comment]
<img width="392" alt="image" src="https://user-images.githubusercontent.com/22636177/197458623-c7744fc5-e98a-45ab-a766-a352c42f44bf.png">
目前只能先自己监听一下了，还是期待能有 Compose 原生的大图超采样支持

**Comment by panpf** [comment]
计划是要有的，等我学完 compose 自定义的

**Comment by panpf** [comment]
单独的 zoomimage （ https://github.com/panpf/zoomimage ）库来了，支持 compose 和 view，两个版本逻辑和体验完全一致

新的 zoomimage 库在 sketch-zoom 的基础上完全重构，用户体验全面提升，除修复了一些 bug 之外还新支持了子采样碎片的动画和清晰度渐变以及支持 glide、picasso、coil、等更多图片加载器

目前已经到了公开测试的 beta 阶段，欢迎到 [release](https://github.com/panpf/zoomimage/releases) 页面下载 APK 体验效果
