### ISSUE TITLE
从 3.1.0-beta01 升级到 3.1.0 出现图片缩放异常

### ISSUE THREAD

**Issue by HuanCheng65** [panpf/sketch#172]
具体表现：Compose 中使用，3.1.0-beta01 时可以占满整个组件，升级后无法占满

升级前：
![3.1.0-beta01](https://user-images.githubusercontent.com/22636177/197457825-fcb0ad65-d725-4c24-aa44-a6518f241dc8.jpg)

升级后：
![3.1.0](https://user-images.githubusercontent.com/22636177/197457796-06faaf91-1d87-4245-9ce4-6e511fd73604.jpg)

组件代码：
<img width="385" alt="image" src="https://user-images.githubusercontent.com/22636177/197458113-3072de8e-0082-4e7b-addf-4ac207c7fbeb.png">

**Comment by panpf** [comment]
data 和 size 的值给出来我试一下

**Comment by HuanCheng65** [comment]
> data 和 size 的值给出来我试一下

http://tb.himg.baidu.com/sys/portrait/item/tb.1.e84bc6e4.fqpFKXLQx6oIQ9OUR5rg1Q
size 是 56.dp

**Comment by HuanCheng65** [comment]
> 我没有复现出你的情况，你的 placeholder 是什么？

一个 GradientDrawable，设置了 color 和 cornerRadius

**Comment by panpf** [comment]
应该是 placeholder 的问题，你换一张真实图片试试

**Comment by HuanCheng65** [comment]
> 应该是 placeholder 的问题，你换一张真实图片试试

去掉 placeholder 仍然不正常，另外发现 beta03 仍然是正常的，问题开始出现于 beta04 上

**Comment by panpf** [comment]
关键是我根据你提供的信息无法复现，你进 QQ 群吧，这样方便沟通

**Comment by panpf** [comment]
QQ：529630740

**Comment by panpf** [comment]
已确认无此问题
