### ISSUE TITLE
你好，如果heic图片里边，是包含多张图片的话，能够播放的嘛？

### ISSUE THREAD

**Issue by TongmingWu** [panpf/sketch#173]
比如说这张图
https://nokiatech.github.io/heif/content/image_sequences/sea1_animation.heic

**Comment by panpf** [comment]
heic 动图在 Android 11 以上可用，详情请参考文档 https://github.com/panpf/sketch/blob/main/docs/wiki/animated_image.md

heic 和 heif 是一样的

**Comment by TongmingWu** [comment]
谢谢！可以播放动图
