### ISSUE TITLE
加载webp动图遇到问题

### ISSUE THREAD

**Issue by yuqingweng** [panpf/sketch#174]
```
 binding.test.displayImage(R.drawable.widgets__ic_loading_small) {
            components {
                addDrawableDecoder(WebpAnimatedDrawableDecoder.Factory())
            }
        }
```
本地的webp注册了decoder也用不了。并且`placeholder(R.drawble.widgets__ic_loading_small)`也无法播放webp图，同时该占位图的位置不是居中的

**Comment by panpf** [comment]
请补充一下完成的代码以及设备、环境信息，以便我能复现

**Comment by yuqingweng** [comment]
设备名：Pixel 2
 `binding.test` 就是一个普通的`imageView`、
[widgets__ic_loading_small.zip](https://github.com/panpf/sketch/files/11177293/widgets__ic_loading_small.zip)

**Comment by panpf** [comment]
系统版本？

**Comment by yuqingweng** [comment]
Android 11

**Comment by panpf** [comment]
webp 播放问题：首先动图必须从本地或 asset 中通过 Decoder 加载，从 resources 中加载的都是静态图片（Android 不支持）
占位图不居中问题：检查你的占位图的内容是否本身就不局中，以及 ImageView 的 ScaleType 设置，再检查不出来请贴出完整代码及资源我来试试

**Comment by yuqingweng** [comment]
可以加载了，placeholder是不是没法加载webp的动图。看了一下只提供drawble int 和stateImage

**Comment by panpf** [comment]
是的，因为动图需要异步线程加载，且无法缓存，不适合用在placeholder。你可以用纯代码的形式做一个会动的作drawable。
