### ISSUE TITLE
希望能增加在newRequest修改uriString的功能

### ISSUE THREAD

**Issue by lr555** [panpf/sketch#175]
在addRequestInterceptor里，自定义了一个拦截器，需要拦截特定的url，通过代理加载，需要修改url，增加header。
现在[request.newRequest](https://github.com/panpf/sketch/blob/main/sketch/src/main/java/com/github/panpf/sketch/request/ImageRequest.kt#L257)不支持修改uriString。虽然可以不用拦截器，用其他方法实现，但是有点麻烦，可以考虑加上这个功能

**Comment by panpf** [comment]
按设计URL参与计算各种key，因此要保持不变。根据你的需求建议自定义 http 网络请求部分，修改URL增加header，这样能将影响控制在最小的范围。

**Comment by lr555** [comment]
> 按设计URL参与计算各种key，因此要保持不变。根据你的需求建议自定义 http 网络请求部分，修改URL增加header，这样能将影响控制在最小的范围。

👌🏻
