### ISSUE TITLE
用了    crossfade() 进行占位图的切换

### ISSUE THREAD

**Issue by yuqingweng** [panpf/sketch#177]
文档内容：如果 result 图片的尺寸比 placeholder 图片大，placeholder 图片在作为过渡的 start 时就会被改变尺寸，在页面上的显示效果就是在过渡的开始时 placeholder 图片会快速的放大，虽然这个过程很快，但还是容易被看出来
但是真实的场景是result被缩小了，然后recycleview上下滑动result图片又变大

**Comment by yuqingweng** [comment]
```
imageView.displayImage(url) {
            crossfade()
        }
```
补充代码的调用

**Comment by panpf** [comment]
这个问题提供了 resizeToDrawable 方式来解决，你可以试一试
