### ISSUE TITLE
Only support AnimatedImageDrawable

### ISSUE THREAD

**Issue by Ninefy** [panpf/sketch#179]
加载某些webP的图片时，会报这个错误
![111](https://github.com/panpf/sketch/assets/52345702/51bed7ed-428a-45f5-b146-56905adcf48f)
以下是图片的url
https://assets-dev.opencord.so/attachments/1684926000000/31363235333837383637373232393532373034da39a3ee5e6b4b0d3255bfef95601890afd80709/42c77cdc-ccb6-4333-ad4e-9e96b779f953_thumbnail.webp?_resize=Resize

目前是这样设置的
![2222](https://github.com/panpf/sketch/assets/52345702/5f23fd0b-c0e0-4b5b-b15a-fe5b1a2aa179)

试过升到3.2.0 beta-2 ,但还是同样的问题

如果去掉 WebpAnimatedDrawableDecoder  ,那么webp 静态图片 能展示，但是webp动图 则只会展示第一帧 ，请问下有什么好的办法能解决这个问题

系统             鸿蒙3.0.0.208
机型             华为mate30
sketch版本  3.1.0

**Comment by panpf** [comment]
这张图片用的是 webp 动图的编码，但其实是只有一帧是静态图，然后就被 WebpAnimatedDrawableDecoder 识别到，解码得到的又不是动图，所以报错，今天会再出一个 beta 版本兼容这个问题

**Comment by panpf** [comment]
3.2.1-beta03 已发布，已兼容此种情况，可以试试了

**Comment by Ninefy** [comment]
感谢，已经修复了

**Comment by panpf** [comment]
建议升级到 v3.2.2 版本，修复了 v3.2.1  版本修复这个问题时带来的 bug

**Comment by panpf** [comment]
你这个 gif 图只有一帧，Android 的解码器就解码成了普通图片，后面我再兼容一下这种情况吧
