### ISSUE TITLE
compose版本加载webp图片出现问题

### ISSUE THREAD

**Issue by yuqingweng** [panpf/sketch#182]
这里不支持显示webp图片，我做了什么，加了webp的动图支持 
`
AsyncImage(
                        imageUri = webp图片地址,
                        contentDescription = null,
                        contentScale = contentScale, modifier = modifier
                    )
`

**Comment by panpf** [comment]
请详细描述运行环境，Android 版本、sketch 版本、设备型号、图片 uri、同样环境下 view 能否播放等信息

**Comment by yuqingweng** [comment]
运行环境 Android Studio Flamingo | 2022.2.1 Patch 2
Android版本是 13 和 9
sketch版本是当前的3.2.0
设备是pixel7 Android13 mezu note 9 Android9 
在view下也无法运行，图片uri无法提供，可以提供原图，但是这里不支持上传，图片uri外部无法访问

**Comment by panpf** [comment]
进 QQ 群 529630740 私聊群主发图片

**Comment by panpf** [comment]
建议升级到 v3.2.2 版本，修复了 v3.2.1  版本修复这个问题时带来的 bug
