### ISSUE TITLE
sketch 初始化能不能放出来，库里面集成没法在Application中配置

### ISSUE THREAD

**Issue by lic2050** [panpf/sketch#186]
给一个外部创建Sketch的方法，而不是写死在Application中

**Comment by panpf** [comment]
你库里面该用用，在 App 里做自定义配置就行了，图片加载框架不适合有多个实例

**Comment by panpf** [comment]
另外也只是默认提供了一个单例实现，但你完全可以不用这个单例，自己创建自己用，只要你自己能把控好风险

**Comment by lic2050** [comment]
这个怎么使用自己提供的sketch，我用的rememberAsyncImagePainter加载图片，看了内部使用
val sketch = LocalContext.current.sketch 获取的sketch，没有看到能替换的方法

**Comment by panpf** [comment]
已发布 3.3.0-beta01，rememberAsyncImagePainter 提供了设置 sketch 的参数，也可以通过 SketchSingleton.setSketch() 方法设置自定义的单例，完全满足你的需求。

详情请参考更新日志和文档 https://github.com/panpf/sketch/blob/main/docs/wiki/getting_started.md#sketch
