### ISSUE TITLE
Missing licenses

### ISSUE THREAD

**Issue by colinrtwhite** [panpf/sketch#191]
Hi, I noticed this library uses a significant portion of [Coil](https://github.com/coil-kt/coil)'s code as a base which is OK, but it doesn't clearly indicate this or include [Coil's license](https://github.com/coil-kt/coil?tab=readme-ov-file#license). Please:

- Include [Coil's license](https://github.com/coil-kt/coil/blob/main/LICENSE.txt#L189) [here](https://github.com/panpf/sketch?tab=readme-ov-file#license) and [here](https://github.com/panpf/sketch/blob/main/LICENSE.txt#L190).
- Clearly indicate in the README that this library uses code derived from Coil. The special thanks section doesn't make this clear. "This library uses portions of code derived from [Coil](https://github.com/coil-kt/coil)." would be clearer.
- Remove your copyright headers from files that were copied and modified from Coil (e.g. [`MovieDrawable`](https://github.com/panpf/sketch/blob/main/sketch-gif-movie/src/main/kotlin/com/github/panpf/sketch/drawable/MovieDrawable.kt), [`AnimatedTransformation`](https://github.com/panpf/sketch/blob/main/sketch-core/src/main/kotlin/com/github/panpf/sketch/transform/AnimatedTransformation.kt), [`ViewTargetRequestManager`](https://github.com/panpf/sketch/blob/main/sketch-core/src/main/kotlin/com/github/panpf/sketch/request/internal/ViewTargetRequestManager.kt), amongst others).

**Comment by panpf** [comment]
Received, these will be added in the next version

**Comment by panpf** [comment]
Version 3.3.0-beta05 has been released, license information has been added
