### ISSUE TITLE
[疑问] 在Compose的Lazy组件中, 可以实现滚动中暂停加载图片吗?

### ISSUE THREAD

**Issue by Raven-L** [panpf/sketch#192]
看View那边有类似的功能, 想问问Compose这边有没有实现. 或者是Compose特性就已经支持了

**Comment by panpf** [comment]
https://github.com/panpf/sketch/blob/main/docs/wiki/pause_load_when_scrolling.md

**Comment by Raven-L** [comment]
感谢, 没发现更新了
