### ISSUE TITLE
AsyncImage只设置宽度没有设置高度时无法显示图片

### ISSUE THREAD

**Issue by RavenLiao** [panpf/sketch#194]
**Sample code**

```
AsyncImage(
    imgUrl,
    null,
    Modifier
        .fillMaxWidth()
        .wrapContentHeight(),
    contentScale = ContentScale.FillWidth
)

```
这种方法加载图片时，无法显示图片，疑似高度为0。
但使用Coil时，能给正常显示图片，是按比例填满宽度显示。
希望能同步实现。

**Versions**

- sketch version*:3.3.1
- Kotlin version*:1.9.22
- Compose version(s)*:1.5.10

**Comment by panpf** [comment]
3.3.2 版本已修复
