### ISSUE TITLE
有的图片明明是正常的，它显示403

### ISSUE THREAD

**Issue by MiChongs** [panpf/sketch#195]
RequestExecutor. Request failed. HTTP status must be 200. 403 . https://img3.doubanio.com/view/photo/l/public/p2603434012.webp

**Comment by MiChongs** [comment]
RequestExecutor. Request failed. HTTP status must be 200. 403 . https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2907242293.jpg

**Comment by MiChongs** [comment]
> RequestExecutor. Request failed. HTTP status must be 200. 403 . https://img3.doubanio.com/view/photo/l/public/p2603434012.webp

这个是403，但有的是正常的它说403

**Comment by MiChongs** [comment]
![image](https://github.com/panpf/sketch/assets/77006751/f4534557-ada3-43eb-93bb-e6409064cead)

**Comment by panpf** [comment]
图片服务器的问题，我在浏览器打开这两张图片的时候头几次也是403 ，后面刷新几次可以显示了
