### ISSUE TITLE
我想问下到底该如何删除指定key的缓存

### ISSUE THREAD

**Issue by MiChongs** [panpf/sketch#196]
我做的软件需要上传头像后删除原头像的缓存，但我照着文档做好像并不行，还是会显示原头像的缓存
![image](https://github.com/panpf/sketch/assets/77006751/fa215230-836f-42db-8f8e-7b16d67fbf03)
![image](https://github.com/panpf/sketch/assets/77006751/9d57f7a0-7067-416b-ac80-655180d14472)

**Comment by panpf** [comment]
假如你的头像 url 是 https://sample.com/avatar.png

那么 downloadCache 的 key 是和 url 一样的，你这么删除没问题

但 resultCache 和 memoryCache 的 key 却是 url 拼接上加载参数的，你直接拿 url 是删不掉的，你应该从 DisplayResult 中取 requestCacheKey，拿这个 requestCacheKey 去删

DisplayResult 需要通过 listener 来获取，详见 https://github.com/panpf/sketch/blob/main/docs/wiki/listener.md

**Comment by MiChongs** [comment]
但我这里使用requestCacheKey还是无法删除好像，使用Editor或Snapshot都不行，还是显示原头像，重启了APP也一样

**Comment by MiChongs** [comment]
> 假如你的头像 url 是 https://sample.com/avatar.png
> 
> 那么 downloadCache 的 key 是和 url 一样的，你这么删除没问题
> 
> 但 resultCache 和 memoryCache 的 key 却是 url 拼接上加载参数的，你直接拿 url 是删不掉的，你应该从 DisplayResult 中取 requestCacheKey，拿这个 requestCacheKey 去删
> 
> DisplayResult 需要通过 listener 来获取，详见 https://github.com/panpf/sketch/blob/main/docs/wiki/listener.md

但我这里使用requestCacheKey还是无法删除好像，使用Editor或Snapshot都不行，还是显示原头像，重启了APP也一样

**Comment by panpf** [comment]
那就需要你 debug 去查查为啥删不掉了
