### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by 1006245347** [panpf/sketch#197]
你好，我看dev-4.0内已经有iOS,什么时候发布完整版，iOS也会跟Android支持同样的功能码，我看你的zoomimage是不支持iOS的，我在coil3加载超长图是会崩溃 ，看你的会不，我是compose multiplatform 。 https://ark-cdn.gree.com/ark/2016c03c4341dae24217fb861ddc5cce_1660720450874.jpg?sign=b123bec45ee8d4f235e6c0b6f95dc2ee&t=1717470000
<img width="225" alt="企业微信截图_9654eb0b-aafa-4493-9679-e02995ebe0b5" src="https://github.com/panpf/sketch/assets/24426708/5fae68d8-8064-4e3b-9700-18b142d87a47">

**Comment by panpf** [comment]
功能已经准备好了，正在写文档，预计还得一到两周，文档准备好后就发布 alpha 版本

**Comment by panpf** [comment]
sketch 发布 compose multiplatform 版本后就会开始开发 zoomimage 的 ios 和 web 版本，因为 zoomimage 需要 sketch

**Comment by panpf** [comment]
sketch 4.0.0 compose multiplatform 版已发布的第一个版本，接下来会在修复 bug 的同时开发 zoomimage 的 ios 版本
