### ISSUE TITLE
在Compose中加载尺寸较小的图片时, 图片非常模糊

### ISSUE THREAD

**Issue by RavenLiao** [panpf/sketch#198]
**Describe the bug**
相较于Coil, Sketch加载某些尺寸的图片时, 总会比较模糊一些:
图像链接: https://drop-assets.ea.com/images/6jp8xRcgC9d1x3W9m5x8Nx/28a273037c4b593de110e3895be7509f/9.png
在同一台设备上, 
使用Coil加载:
![image](https://github.com/panpf/sketch/assets/47520028/5cd1535d-744a-4e4c-b2e1-e398e27c54bf)
使用Sketch加载:
![image](https://github.com/panpf/sketch/assets/47520028/d03428d4-e86e-4b7b-836c-295d559cf87b)

UI像素宽高 :168x108

可以明显看到Sketch的图像糊成一片了, 希望可以尽快排查修复

**Versions**

- sketch version*:3.3.2
- Kotlin version*:2.0.0
- Compose version(s)*:vom 2024.05.00

**Comment by panpf** [comment]
图片大小相关的问题请查看文档：https://github.com/panpf/sketch/blob/main/docs/wiki/resize_zh.md

**Comment by RavenLiao** [comment]
> 图片大小相关的问题请查看文档：https://github.com/panpf/sketch/blob/main/docs/wiki/resize_zh.md

我加载时没有用resize参数, 两边都是默认加载的

尝试添加
resizeApplyToDrawable()
和
resizePrecision(FixedPrecisionDecider(Precision.SAME_ASPECT_RATIO))
都没有改善

**Comment by RavenLiao** [comment]
> 图片大小相关的问题请查看文档：https://github.com/panpf/sketch/blob/main/docs/wiki/resize_zh.md

可以排查一下这个问题吗? 因为这个影响还挺大的, 尝试了没有作用。
调用没有使用其他参数，只使用url参数进行加载

**Comment by panpf** [comment]
加大 resizeSize

**Comment by RavenLiao** [comment]
> 加大 resizeSize

确实resizeSize设置成UI尺寸的两倍之后，清晰了很多，但这样有点太麻烦了吧，总不能所有加载的地方都使用这个，很多情况下都是不确定尺寸的。

有更好的解决方案吗？

**Comment by panpf** [comment]
在现有逻辑下只有 resizeSize 特别小的时候可能才会有这种情况，针对这种情况你可以加一个全局的 RequestInterceptor，resizeSize 特别的时候你主动给他加大一些

**Comment by panpf** [comment]
https://github.com/panpf/sketch/blob/main/docs/wiki/request_interceptor.md

**Comment by RavenLiao** [comment]
> 在现有逻辑下只有 resizeSize 特别小的时候可能才会有这种情况，针对这种情况你可以加一个全局的 RequestInterceptor，resizeSize 特别的时候你主动给他加大一些

尝试了一下， 暂时解决了。
但还是希望可以改善一下逻辑，毕竟这样的策略太治标不治本了。辛苦大佬了
