### ISSUE TITLE
iOS加载只有一帧的gif图片，会crash

### ISSUE THREAD

**Issue by lizhaolin09** [panpf/sketch#205]
**Describe the bug**

iOS加载只有一帧的gif图片，会crash，demo可以复现。

**Versions**

- sketch version*:  v4.0.0-alpha05
- Kotlin version*:  2.0.0
- Compose version(s)*: 1.6.11
- Running Devices (*) (Model, OS, CPU Architecture, JDK.):
    - iphone 11 pro max; iOS 17.5.1; arm64

**Sample code**

If possible, provide a small piece of code that reproduces the problem. If the code snippet is too
large to paste here, please link to a Gist, a GitHub repo, or any other public code repository.

**Reproduction steps**

将demo中的加载的gif替换成一张只有一帧的gif，运行之后crash

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by panpf** [comment]
请好好填写 bug 模板 🥲

**Comment by lizhaolin09** [comment]
> 请好好填写 bug 模板 🥲

填了

**Comment by panpf** [comment]
直接把你出问题的图片打个压缩包发出来

**Comment by lizhaolin09** [comment]
[FpRlL4zAdNpY_bHlURXrBuYBn-nF.gif.zip](https://github.com/user-attachments/files/16517827/FpRlL4zAdNpY_bHlURXrBuYBn-nF.gif.zip)


> 直接把你出问题的图片打个压缩包发出来

**Comment by panpf** [comment]
Reproduced, fixed soon, you can also fix it yourself and then pull request

**Comment by panpf** [comment]
Fixed in version v4.0.0-alpha06
