### ISSUE TITLE
在iOS播放 gif 或者 webp 图片时候，效果异常

### ISSUE THREAD

**Issue by DrXbobo** [panpf/sketch#206]
**Describe the bug**
替换demo中 gif 和 webp 图片，运行iOS sample，发现图片某些帧渲染异常

**Versions**

- sketch version*: 4.0.0 -alpha06
- Kotlin version*: 2.0.0
- Compose version(s)*: 1.6.10
- Running Devices (*) (Model, OS, CPU Architecture, JDK.):
    - iphoneXs, iOS 17.5.1, arm64

**Sample code**

**Reproduction steps**

**Expected behavior**

**Screenshots**

**Additional context**

测试图片
[test.zip](https://github.com/user-attachments/files/16655387/test.zip)

**Comment by panpf** [comment]
已复现，近期修复

**Comment by DrXbobo** [comment]
您的来信已收到

**Comment by panpf** [comment]
已于 4.0.0-alpha07 版本修复
\----
Fixed in version 4.0.0-alpha07
