### ISSUE TITLE
Advantages over coil

### ISSUE THREAD

**Issue by T8RIN** [panpf/sketch#216]
Why should i use sketch and not coil? I mean the purpose of this library

**Comment by panpf** [comment]
Coil is a very good library, we all like it.

Sketch is more of a precipitation of my image loading needs in the process of developing apps, and then it is designed with reference to the functions and general needs of other libraries.

For example, my understanding of the implementation of size, in most cases I only need the number of pixels of the final image after sampling to be less than size, and there is no need to scale the image to make its width or height equal to size (the default implementation of coil)

For example, I have the need to load APK and installed App icons, so I implement and provide optional modules

Or I have the need to display the image type, so I include the original size and mimeType of the image in the return result, and then implement and provide optional modules to support it

I have the need not to load images in cellular network state, so I designed the depth parameter and then implemented and provided optional modules to support it

**Comment by T8RIN** [comment]
Thanks!
