### ISSUE TITLE
4.0.0-beta01 gradle sync failed 

### ISSUE THREAD

**Issue by DrXbobo** [panpf/sketch#217]
![img_v3_02ge_8b59aa94-1bda-4dc5-b65f-bfc6481afc9g](https://github.com/user-attachments/assets/2bb05455-c73b-47cc-a168-7d66d7beb314)

change version to v4.0.0-beta01，then sync failed , What else do I need to do?

**Comment by panpf** [comment]
The 4.0.0-beta01 version no longer contains the sketch-animated module. It has been split. Please check the change log and readme to change the dependency.

**Comment by DrXbobo** [comment]
您的来信已收到
