### ISSUE TITLE
Context for the cache 

### ISSUE THREAD

**Issue by AntonAlekseevich93** [panpf/sketch#218]
Help please. The instructions for Sketch.Builder(context) always require context. However, nowhere does it say how to get this context for desktop or iOS

**Comment by panpf** [comment]
Use PlatfornContext.INSTANCE directly

**Comment by AntonAlekseevich93** [comment]
I've tried it but I always get it: e: file:///Users/aAndroidStudioProjects/YourLibrary/common/cache-manager/data/src/commonMain/kotlin/ImageCacheManagerImpl.kt:16:25 Unresolved reference 'INSTANCE'.
