### ISSUE TITLE
sketch-animated-heif sync error

### ISSUE THREAD

**Issue by IacobIonut01** [panpf/sketch#220]
Failed to resolve: sketch.internal:test:unspecified
Failed to resolve: sketch.internal:test-singleton:unspecified

sketch version: `4.0.0-beta01`

**Comment by IacobIonut01** [comment]
https://repo1.maven.org/maven2/io/github/panpf/sketch4/sketch-animated-heif/4.0.0-beta01/sketch-animated-heif-4.0.0-beta01.pom

**Comment by panpf** [comment]
Fixed in v4.0.0-beta02
