### ISSUE TITLE
Images are not loaded in the beta version

### ISSUE THREAD

**Issue by AntonAlekseevich93** [panpf/sketch#221]
I can't figure out what the problem is, but in all versions v4.0.0-beta01, v4.0.0-beta02, v4.0.0-beta03, image loading does not work. They just don't load. Does anyone have the same problem? The alpha version is working fine
```
AsyncImage(
                                request = ComposableImageRequest("....") {
                                    scale(Scale.FILL)
                                    placeholder(Res.drawable.ic_default_book_cover_7)
                                    error(Res.drawable.ic_default_book_cover_7)
                                },
                                contentScale = ContentScale.FillBounds,
                                contentDescription = null,
                            )
```

**Comment by AntonAlekseevich93** [comment]
And in the previous version, you fixed the cache cleanup. The sketch.downloadCache.clear() method does not work. If you call him. And then turn off the Internet, the picture remains in memory.

**Comment by panpf** [comment]
> I can't figure out what the problem is, but in all versions v4.0.0-beta01, v4.0.0-beta02, v4.0.0-beta03, image loading does not work. They just don't load. Does anyone have the same problem? The alpha version is working fine
> 
> ```
> AsyncImage(
>                                 request = ComposableImageRequest("....") {
>                                     scale(Scale.FILL)
>                                     placeholder(Res.drawable.ic_default_book_cover_7)
>                                     error(Res.drawable.ic_default_book_cover_7)
>                                 },
>                                 contentScale = ContentScale.FillBounds,
>                                 contentDescription = null,
>                             )
> ```

I have tested it on both Android and desktop platforms and it can load normally. Can you provide more information? For example, uri.

In addition, starting from the beta version, you need to configure the http module to load images with http uri. If your uri is http uri, please refer to the document to configure the http module

**Comment by panpf** [comment]
> And in the previous version, you fixed the cache cleanup. The sketch.downloadCache.clear() method does not work. If you call him. And then turn off the Internet, the picture remains in memory. That is, I uploaded the image to the Alpha version, then made the beta version. The image is stored in the cache. I'm clearing, the picture is not being cleared. But new images are not loaded on beta.

Please go to https://github.com/panpf/sketch/issues/219 to discuss this issue

**Comment by panpf** [comment]
Is there any new progress?
