### ISSUE TITLE
如何在composeResource里解码svg文件？

### ISSUE THREAD

**Issue by kagg886** [panpf/sketch#222]
rt(

**Comment by panpf** [comment]
使用 newComposeResourceUri() 创建专用 uri，即可

**Comment by kagg886** [comment]
目前是这样的：
```kotlin
rememberAsyncImagePainter(
      request = ComposableImageRequest(
            uri = Res.getUri("drawable/copy.svg")
      )
)
```
有没有办法可以传入DrawableResource（如`Res.drawable.copy`）来获取painter？Android端不支持`paintResource()`传入svg的方式

**Comment by panpf** [comment]
uri 只能接收 String

**Comment by kagg886** [comment]
那希望可以做一个接收DrawableResource参数以返回可绘制svg的Painter(

~~直接填uri的话有点不太好其实~~

**Comment by panpf** [comment]
你的主要目的是什么？由于无法访问 DrawableResource 的 ID，就拿不到图片的真实 uri，就无法在加载过程中访问原始文件流。
sketch 是要访问原始文件流才能发挥其价值，否则的话为什么不直接通过 painterResource 获取 painter 直接显示
