### ISSUE TITLE
错误占位图显示问题

### ISSUE THREAD

**Issue by aaaorange** [panpf/sketch#225]
把SketchZoomImageView添加进viewPager,错误占位图显示时会铺满viewPager，怎么调整大小

**Comment by panpf** [comment]
SketchZoomImageView 就是一个普通的 ImageView，它没有什么特别的，你在使用 ImageView 的时候怎么避免图片铺满 ViewPager，SketchZoomImageView 就怎么避免，一模一样的

关于占位图 Sketch 提供了几种 StateImage 也许可以间接的满足你的需求，仅供参考
https://github.com/panpf/sketch/blob/main/docs/wiki/state_image_zh.md

**Comment by aaaorange** [comment]
> SketchZoomImageView 就是一个普通的 ImageView，它没有什么特别的，你在使用 ImageView 的时候怎么避免图片铺满 ViewPager，SketchZoomImageView 就怎么避免，一模一样的
> 
> 关于占位图 Sketch 提供了几种 StateImage 也许可以间接的满足你的需求，仅供参考 https://github.com/panpf/sketch/blob/main/docs/wiki/state_image_zh.md

已经解决，谢谢
