### ISSUE TITLE
部分大图  放大后，有空白线

### ISSUE THREAD

**Issue by shenqinci** [panpf/sketch#31]
1. 如示例里面的地图和黑圈，放大后，在部分切块交接边沿有空白线(有的手机看起来像黑线，有的手机看起来是透明的线，显示底下模糊背景)（看起来像是切片小了一个像素，放大到最大，或者缩小到最小就没有线）

2. 示例里的微博长度，每块切片的加载时间，会越来越长，不断上下滑动，每次切片的时间会递增

**Comment by xiaopansky** [comment]
第一个问题，我这边试了几个手机没有复现你说的情况，你能否给个截图
第二个问题，刚使用这张长微博图片的时候就发现了这个情况，但是百般尝试找不到原因，并且其它的长图片都是好好的只有这张图片会这样，希望你能找到不一样的线索
