### ISSUE TITLE
占用内存过大 退出Activity不释放内存

### ISSUE THREAD

**Issue by hansionit** [panpf/sketch#36]
举例：在Unsplash这个界面点击其中一张图进入单张浏览页面，一共有20张图，从第一张滑动到最后一张，APP占用内存增加了35兆以上（进入APP时占用31.31M,滑动完成后占用67.51M），在退出该Activity的时候不释放内存。其他的的页面看图片也是这样的

**Comment by xiaopansky** [comment]
Sketch有两层内存缓存，一个是LruMemoryCache，一个是BitmapPool，必然会占用较多内存。每个的内存占用数据你都可以在侧滑菜单中看到，Sketch会根据需要以及内存状况自动释放。至于使用缓存的目的就是重复利用资源，减少内存抖动
