### ISSUE TITLE
not support https

### ISSUE THREAD

**Issue by fccaikai** [panpf/sketch#38]
不支持https图片地址

**Comment by panpf** [comment]
你给我一张https的图片地址 我试试

**Comment by fccaikai** [comment]
https://img.evalshell.com:88/images/2/2017/06/GVhi4ho33HHw30hWvYhyVnyUoY8VtW.jpg
提示是没有证书

**Comment by panpf** [comment]
你这张图片用 浏览器访问 浏览器提示 不安全 貌似这个网站的证书有问题  我回头再找些https图片试试

**Comment by panpf** [comment]
如果你有特殊的需求你可以自定义 HttpStack https://github.com/panpf/sketch/blob/master/docs/wiki/http_stack.md

**Comment by fccaikai** [comment]
谢谢
