### ISSUE TITLE
关于GaussianBlurImageProcessor用法

### ISSUE THREAD

**Issue by 973562634** [panpf/sketch#39]
GaussianBlurImageProcessor make = GaussianBlurImageProcessor.make();
            DisplayHelper helper = new DisplayHelper();
            helper.processor(make);
小弟是这么写的，但是好像不对啊，求指教

**Comment by asker517** [comment]
[参考这里](https://github.com/panpf/sketch/blob/master/sample/src/main/java/me/xiaopan/sketchsample/fragment/GaussianBlurImageProcessorTestFragment.java)

**Comment by panpf** [comment]
DisplayHelper不是你自己new的 得有Sketch的display方法返回
