### ISSUE TITLE
More zoom in SketchImageView

### ISSUE THREAD

**Issue by JEKos** [panpf/sketch#41]
Hi,
I want to have more zoom in SketchImageView
I'm doing the code below but zoom doesn't change to 20f, but remain the default zoom

```
val photoView = SketchImageView(container.context)
photoView.isZoomEnabled = true
photoView.imageZoomer.zoom(20f)
photoView.options.setImageDisplayer(FadeInImageDisplayer())
photoView.displayImage("http://www.examplelink.com/example.jpg")
```

**Comment by panpf** [comment]
The zoom () method is only valid after the picture is displayed. You can register the display completion with the SketchImageView.setDisplayListener () method.

**Comment by JEKos** [comment]
I'm do it after the picture is displayed but it's still the same.

```
val photoView = SketchImageView(container.context)
photoView.options.setImageDisplayer(FadeInImageDisplayer())
photoView.displayImage("http://www.examplelink.com/example.jpg")
photoView.isZoomEnabled = true
photoView.imageZoomer.zoom(20f)
```

**Comment by panpf** [comment]
You can write (Java version)

```
photoView.setZoomEnabled(true)
photoView.setDisplayListener(new DisplayListener(){
        public void onCompleted(Drawable drawable, ImageFrom imageFrom, ImageAttrs imageAttrs){
            ImageZoomer imageZoomer = photoView.getImageZoomer();
            imageZoomer.zoom(imageZoomer.getMaxZoomScale());
        }
});
photoView.displayImage("http://www.examplelink.com/example.jpg")
```

note:
* Zoom (float) parameter value can not be greater than imageZoomer.getMaxZoomScale ()
* You can check the return value of the zoom (float) method, and if it is false, the execution fails

**Comment by JEKos** [comment]
In Photoview you can add `photoView.maximumScale = 20f` to increase the maximum scale you can zoom in the photo, is there any same way for SketchView ?

**Comment by panpf** [comment]
Sorry, there is no such way.
PhotoView is the fixed maximum zoom scale, but I do not think this does not apply to all sizes of images, so SketchImageView calculates the optimal maximum scaling based on the size of the image and the size of the phone screen on PhotoView
