### ISSUE TITLE
base64 图片加载问题  

### ISSUE THREAD

**Issue by f987002856** [panpf/sketch#42]
你好，我在使用本框架的时候，有用到 base64 加载图片，在使用中，发现文档有一处写错了，还请查看下是否存在此问题。
文档描述：
// display base64 image
sketchImageView.displayImage("data:image/jpeg;base,/9j/4QaO...U7T/in//Z");

源码中调用方式：
UriScheme 第 127 行：
return uri.substring(uri.indexOf(";") + ";base64,".length());

我目前使用方式，可以正确显示图片：
imageView.displayImage("data:image/jpeg;" + ";base64," + data.getImage());

如果用户调用文档的方式，控制台会显示 base64 解码错误，会让用户产生一个小误解，以为是 图片错误。请查看是否存在这个问题o(*￣︶￣*)o

**Comment by panpf** [comment]
感谢你的反馈，文档已经更新！
