### ISSUE TITLE
Rotate :

### ISSUE THREAD

**Issue by arunramya** [panpf/sketch#46]
I have a image viewer app. i want to rotate image from portrait to landscape view & similarly rotate image from landscape to portrait. How to do that via sketch.

**Comment by panpf** [comment]
You need to turn on the zoom function first:
```java
SketchImageView sketchImageView = ...;
sketchImageView.setZoomEnabled (true);
```

And then execute when the user triggers the rotation operation:
```java
sketchImageView.getImageZoomer (). rotateTo (90)
```

Reference Documents https://github.com/panpf/sketch/blob/master/docs/wiki/zoom.md

**Comment by arunramya** [comment]
My code is:

i compiled your library as follows.

    compile 'me.xiaopan:sketch:2.4.0-beta1'
    compile 'me.xiaopan:sketch-gif:2.4.0-beta1'

Activity code :

SketchImageView image = (SketchImageView) findViewById(R.id.image_rotate);
        image.setSupportZoom(true);
        //image.setRotation(90);
        image.getImageZoomer().setReadMode(true);
        image.getImageZoomer().rotateTo(90);


but image not rotated, please kindly check this once.

**Comment by arunramya** [comment]
My code is:

i compiled your library as follows.

    compile 'me.xiaopan:sketch:2.5.0-b2'
    compile 'me.xiaopan:sketch-gif:2.5.0-b2'

Activity code :

SketchImageView imagev = (SketchImageView) findViewById(R.id.image_rotate);
imagev.setZoomEnabled(true);
image.getImageZoomer().rotateTo(90);

but image not rotated, please kindly check this once.

**Comment by panpf** [comment]
请注意 log 中的 `"ImageZoomer. not working. rotateTo"` 

rotateTo 方法必须在图片显示完成以后才能工作，所以你必须收到 onCompleted 事件后执行 rotateTo，如下：
```java
SketchImageView imagev = (SketchImageView) findViewById(R.id.image_rotate);
imagev.setZoomEnabled(true);
imagev.setDisplayListener(new DisplayListener() {
    ...

    @Override
    public void onCompleted(Drawable drawable, ImageFrom imageFrom, ImageAttrs imageAttrs) {	
        imagev.getImageZoomer().rotateTo(90);
    }
});

imagev.displayImage("http://t.cn/RShdS1f");
```

**Comment by arunramya** [comment]
Thank you. its working amazing.
