### ISSUE TITLE
Bitmap:

### ISSUE THREAD

**Issue by arunramya** [panpf/sketch#47]
How to get bitmap from sketch Image View. Please give me an answer.

**Comment by panpf** [comment]
Do not recommend that you get the bitmap from SketchImageView and then work on the bitmap, because SketchImageView bitmap is managed by Sketch, you can Sketch.with().load() method to get uri bitmap

If you just want to view the SketchImageView bitmap, you can do that
```java
sketchImageView.setDisplayListener(new DisplayListener() {
    ...

    @Override
    public void onCompleted(Drawable drawable, ImageFrom imageFrom, ImageAttrs imageAttrs) {
		Drawable lastDrawable = SketchUtils.getLastDrawable(drawable);
		if (lastDrawable != null && lastDrawable instanceof BitmapDrawbale) {
		    BitmapDrawable bitmapDrawable = (BitmapDrawable) lastDrawable;
		    Bitmap bitmap = bitmapDrawable.getBitmap();
		}
    }
});
```
