### ISSUE TITLE
Image Thumbnail:

### ISSUE THREAD

**Issue by arunramya** [panpf/sketch#48]
By default sketch image View does not use Exif to show thumbnail.  how can i do this ? Because some devices have issues (like samsung j2)

**Comment by panpf** [comment]
I do not understand what you mean please describe in detail

**Comment by arunramya** [comment]
i have two images in my camera directory on my phone (Samsung j2) . one image taken as portrait, another one taken as landscape. if i am using sketch image view, thumbnails are shown incorrect (Ex: portrait image thumbnail shown as landscape, landscape image thumbnail shown as portrait).

**Comment by panpf** [comment]
Starting with version 2.4.0, Sketch defaults through the exif information to correct the orientation of the image. If the image you see is still incorrect, it means that the image does not contain exif information. Sketch is powerless

**Comment by arunramya** [comment]
Ok Thank you.
