### ISSUE TITLE
手势缩放问题

### ISSUE THREAD

**Issue by a1227308812** [panpf/sketch#49]
在开启手势缩放之后在列表中滑动的时候，划过几张图片之后手势缩放失效，并且在处于图片被手动缩小了之后再滑动过几张图片之后会导致所有图片都缩小了，然后手势缩放还失效了，就变不会来了，这是什么原因啊？我在列表中不开手势缩放到还没感觉出上面的问题

**Comment by panpf** [comment]
1. 列表中开启手势缩放来回滑动后手势缩放失效，这确实是一个bug，下版本会修复
2. 列表中确实不应该开启手势缩放，会跟列表的滑动冲突，体验不好
