### ISSUE TITLE
onComplete方法的监听不管用

### ISSUE THREAD

**Issue by YaweiWang** [panpf/sketch#50]
我现在需要实现这样一个功能，在一个gif播放完以后播放另一个git，我在前一个gif的onComplete方法中调用播放第二个gif的代码，但是两个gif并没有实现先后播放，而是同时播放。多谢楼主！

**Comment by panpf** [comment]
我从来没有在任何文档中说过 onCompleted 方法是 GIF 播放完成的回调，我可不背这个锅哦 😢

gif 方面的控制你可以直接参考 [Android Gif Drawable](https://github.com/koral--/android-gif-drawable) 

谢谢你的惠顾

**Comment by YaweiWang** [comment]
不好意思，是我的锅。
