### ISSUE TITLE
设置圆形图片怎么用的？

### ISSUE THREAD

**Issue by a1227308812** [panpf/sketch#51]
![image](https://user-images.githubusercontent.com/21053292/31923498-6b0bc1dc-b8ad-11e7-8de9-160841bf02dd.png)
这个链接失效了

**Comment by a1227308812** [comment]
原先的链接失效了，希望可以出一个关于生成一个任意形状的图形控件的demo和api文档，还有几十职业中的demo apk的下载链接也失效了。希望大大关注下

**Comment by panpf** [comment]
https://github.com/panpf/sketch/blob/master/docs/wiki/image_shaper.md
