### ISSUE TITLE
gif默认在wifi状态才自动播放，手机流量状态点击才给与播放

### ISSUE THREAD

**Issue by zwping** [panpf/sketch#53]
如题，请问这个有现成的实现方案嘛？

**Comment by panpf** [comment]
首先全部开启点击播放GIF，然后通过 OptionsFilter，wifi 状态下强制设置所有 decodeGifImage 为 true，非 wifi 状态下强制为 false 即可

**Comment by panpf** [comment]
OptionsFilter 文档 https://github.com/panpf/sketch/blob/master/docs/wiki/options_filter.md

**Comment by zwping** [comment]
thx，还未看到setClickPlayGifEnabled()，继续了解所有api中。

**Comment by panpf** [comment]
所有的功能，都在 readme 上附上文档链接了，欢迎进群 交流 529630740
