### ISSUE TITLE
怎么加载网络图片

### ISSUE THREAD

**Issue by YaweiWang** [panpf/sketch#54]
Sketch.with(context).download或者load方法拿到的result如何在SketchImageView中展示，示例只是说要先下载后加载，但是没有找到下载后怎么展示，多谢答主。

**Comment by panpf** [comment]
展示图片你用 Sketch.with(context).display() 方法

**Comment by YaweiWang** [comment]
直接在display里面传入图片url和SketchImageView对象吗？那如果要自动播放通过网络url获取的gif图呢？

**Comment by YaweiWang** [comment]
if (url.substring(url.length() - 3, url.length()).equals("png")) {
                holder.gifDecoration.setVisibility(View.VISIBLE);
                Sketch.with(mContext).display(url, holder.gifDecoration).commit();
            } else {
                holder.gifDecoration.setVisibility(View.VISIBLE);
                holder.gifDecoration.getOptions().setDecodeGifImage(true);
                Sketch.with(mContext).display(url, holder.gifDecoration).commit();
            }

**Comment by YaweiWang** [comment]
这是我的代码，url可以在浏览器中加载出图片，但是用SketchImageView加载不出来，以前加载的是本地的图片是正常的。

**Comment by panpf** [comment]
你说的那些都是有文档的，希望你先好好看文档，就在 README 里都有链接

**Comment by panpf** [comment]
另外 显示不出来的话 看下 logcat 中有没有输出 错误 log，根据 Sketch 关键字 过滤一下
