### ISSUE TITLE
大佬有请求图片设置Header实现防盗链的案例吗

### ISSUE THREAD

**Issue by dingyong666** [panpf/sketch#55]
大佬有请求图片设置Header实现防盗链的案例吗

**Comment by panpf** [comment]
很抱歉，我也没有这方面的经验

**Comment by dingyong666** [comment]
就是在 request 的时候 给 请求 添加上 Header

**Comment by panpf** [comment]
你不是要实现防盗链吗？这应该是服务端的工作

**Comment by dingyong666** [comment]
图片开启了防盗链，需要在请求图片的请求上面设置Header

**Comment by panpf** [comment]
那你这就是要破解防盗链，我也没弄过，需要研究

**Comment by panpf** [comment]
你给我发一张加了防盗链的图片地址

**Comment by dingyong666** [comment]
https://static.api1234.com/upload/img/3u90ux01.jpg  设置来源 bt.lmcw.cn

**Comment by panpf** [comment]
你那张图片我试了没问题 浏览器可以访问

**Comment by dingyong666** [comment]
防盗链没设置好，大佬可以用qq空间的图片试验一下

**Comment by android-xiaowei** [comment]
@dingyong666 http://blog.csdn.net/wangsf1112/article/details/73188977看下是这样类似的吗，可以参考下？
