### ISSUE TITLE
关于sketchImageView怎么让其设置为不触发手势放大缩小/移动

### ISSUE THREAD

**Issue by linarykai** [panpf/sketch#57]
大神您好，
    sketchImageView怎么让其设置为不触发手势放大缩小/移动，有没相关Api对其开关设置
打算单独在外面做手势处理 。
     盼答复···

**Comment by panpf** [comment]
你不开起手势缩放不就行了

**Comment by linarykai** [comment]
imageZoomer.setZoomable(false);

**Comment by panpf** [comment]
默认是关闭的 你不需要这么设置

**Comment by linarykai** [comment]
Thanks
