### ISSUE TITLE
Render image from byte / stream 

### ISSUE THREAD

**Issue by varoon** [panpf/sketch#61]
We have an encrypted file. The file has 0 to 250000 bytes
The actual image is starting from 10000 to 250000 

Don't want to save this bytes as a image file. 
Just need to render directly.

Is this possible ? any solution

**Comment by panpf** [comment]
You can solve this problem by customizing UriModel, refer to https://github.com/panpf/sketch/blob/master/sample/src/main/java/me/panpf/sketch/sample/util/XpkIconUriModel.java
The key is to get the getContent (Context, String) method to return an InputStream with encrypted files from 10000 to 250000
