### ISSUE TITLE
Bitmap

### ISSUE THREAD

**Issue by arunramya** [panpf/sketch#62]
Get bitmap from  inputstream.  Please help me how to call via Sketch.

**Comment by panpf** [comment]
I do not understand your needs, please elaborate

**Comment by arunramya** [comment]
i got stream from file, through this stream how can i get bitmap?

**Comment by arunramya** [comment]
FileInputStream initialStream44 = new FileInputStream(new File(Environment.getExternalStorageDirectory() + "/output.jpg"));
                byte[] bufferr = new byte[initialStream44.available()];
                initialStream44.read(bufferr);

Here how can i get bitmap by passing initialStream44. Please Help me.

**Comment by panpf** [comment]
Does not support reading bitmap directly from the input stream, if you know the path to the file, use the file path

**Comment by arunramya** [comment]
i know file path. but the file content contains two images. but i have got second image contents via stream. but now i want to get bitmap for the stream..

**Comment by panpf** [comment]
这个问题你可以通过自定义 UriModel 解决，可参考 https://github.com/panpf/sketch/blob/master/sample/src/main/java/me/panpf/sketch/sample/util/XpkIconUriModel.java 

你需要自定义两个 UriModel，分别用来读取同一个文件中不同的图片

**Comment by arunramya** [comment]
I have implemented what you told. 

How can i call that custom uri model while display bitmap?

**Comment by arunramya** [comment]
private class XpkIconUriModel extends AbsStreamDiskCacheUriModel
  {

    private ByteArrayInputStream myInputStream;

    @NonNull
    @Override
    protected InputStream getContent(@NonNull Context context, @NonNull String uri) throws GetDataSourceException
    {


      FileInputStream strem = null;
      try
      {
        strem = new FileInputStream(uri);
        byte[] xxxx = new byte[strem.available()];
        strem.read(xxxx,0,xxxx.length);      

      } catch (Exception e)
      {
        e.printStackTrace();
        Log.e("Exception Here","oh sorry");
      }


      return strem;
    }

    @Override
    protected boolean match(@NonNull String uri)
    {
      return false;
    }
  }

**Comment by panpf** [comment]
An introduction to uri mode and a custom tutorial here https://github.com/panpf/sketch/blob/master/docs/wiki/uri_model.md

You can translate it to see
