### ISSUE TITLE
初始显示图片不清晰，放大手势后变清晰

### ISSUE THREAD

**Issue by huangbaohuacn** [panpf/sketch#63]
![screenshot_2018-01-16-17-51-49 1](https://user-images.githubusercontent.com/3349095/34982868-ad956d98-fae6-11e7-84e4-da613bf75037.png)
![screenshot_2018-01-16-17-51-58 1](https://user-images.githubusercontent.com/3349095/34982882-b64204ce-fae6-11e7-8227-912edaab7918.png)
请问这是什么原因造成的呢，原图尺寸是1242*2208，手机尺寸1080*1920

**Comment by panpf** [comment]
图片比你的设备屏幕大，初始显示的是缩略图，手势放大后分块显示原图

**Comment by huangbaohuacn** [comment]
能否设置一个范围，范围内都显示原图，只有当图片比设备尺寸大很多时才显示缩略图？

**Comment by panpf** [comment]
这是根据默认 maxSize 决定的，你这里默认 maxSize 应该是屏幕宽高，你这张图片刚好超过你这屏幕宽高一点点，你可以手动指定一个大一些的 maxSize，但是指定了更大的 maxSize 有什么不好的影响你自己可要考虑清楚
