### ISSUE TITLE
设置SketchImageView.setImageShaper()对默认加载图没有生效

### ISSUE THREAD

**Issue by lizhiwei92** [panpf/sketch#68]
如题，使用SketchImageView.setImageShaper()，设置了圆角矩形图片，只对加载完成的图片有用，正在加载中的默认图片没有生效，希望能够优化一下，谢谢。

**Comment by panpf** [comment]
请使用 SketchImageView.getOptions().setShaper()
文档链接：https://github.com/panpf/sketch/blob/master/docs/wiki/image_shaper.md
