### ISSUE TITLE
SketchImageView.setImageShaper()，设置了圆角矩形图片，加载gif时不支持！

### ISSUE THREAD

**Issue by lizhiwei92** [panpf/sketch#69]
SketchImageView.setImageShaper()，设置了圆角矩形图片，加载gif时不支持！仍然显示正常直角图片

**Comment by panpf** [comment]
gif 是集成的 android-gif-drawable，它里面的 bitmap 不受 sketch 控制，因而无法使用任何 sketch 的处理效果
