### ISSUE TITLE
双指对图片进行缩放时，稍微放大，查看图片中建筑边缘有锯齿,放到最大则不会

### ISSUE THREAD

**Issue by DenisZheng** [panpf/sketch#70]
双指对图片进行缩放时，稍微放大，查看图片中建筑边缘有锯齿,放到最大则不会
缩放过程中是否有抗锯齿?

**Comment by DenisZheng** [comment]
方法1：
`paint.setAntiAlias(true);`
`paint.setFlags(Paint.ANTI_ALIAS_FLAG|Paint.FILTER_BITMAP_FLAG);`

方法2：
`canvas.setDrawFilter(new PaintFlagsDrawFilter(0, Paint.ANTI_ALIAS_FLAG|Paint.FILTER_BITMAP_FLAG));`

**Comment by panpf** [comment]
并没有开启抗锯齿，可以考虑加入此项优化，但还得评估是否会对性能造成比较大的影响

**Comment by DenisZheng** [comment]
我在本地download的工程中，在BlockDisplayer中加入抗锯齿代码，编译后查看Demo，缩放过程中的锯齿有所优化，但还未评估性能影响

**Comment by DenisZheng** [comment]
附测试图片
另外一个问题，查看附件图片时，缩放时可看到右上角天空有摩尔纹，使用options.setBitmapConfig设置RGB_8888都无法消除,用手机自带的图库查看则无问题
![pixel2_test](https://user-images.githubusercontent.com/3062447/37443947-0dd53b6c-284a-11e8-9e8f-2496815feede.jpg)
