### ISSUE TITLE
VectorDrawable

### ISSUE THREAD

**Issue by qiushui95** [panpf/sketch#72]
app:srcCompat="@drawable/ic_personal_suggest_upload"貌似没有效果
我想显示矢量图 需要怎么操作,没有找到相关介绍

**Comment by panpf** [comment]
SketchImageView 没有针对 VectorDrawable 做适配，也没有对默认的 ImageView 设置图片的方式做任何改变，据我所知要想用 srcCompat 属性显示矢量图，需要让 Android Studio 在编译器将 ImageView 替换为 AppCompatImageView 才可以
