### ISSUE TITLE
git 不播放

### ISSUE THREAD

**Issue by jasonLYF** [panpf/sketch#74]
demo中无论是网络资源还是本地资源
在GIF MENU 中 把各种情况都设置测试过一遍，
总是出现 gif图不播放的情况。。。
help ！！！

**Comment by panpf** [comment]
我的 demo？

**Comment by jasonLYF** [comment]
自己编译跑的  所有的都不会播放  因为对kotlin不太熟悉 暂时只找到          options.isDecodeGifImage = true  这里

**Comment by panpf** [comment]
自己跑的要注意 build variants 那里选择 normal
