### ISSUE TITLE
ImageDecoder. Decode failed. Unable read bound information. Disk cache deleted.

### ISSUE THREAD

**Issue by 501956430** [panpf/sketch#77]
<img width="1321" alt="2018-07-04 04 35 15" src="https://user-images.githubusercontent.com/20204491/42243396-c4794b74-7f43-11e8-8921-b2ca409d0db3.png">
图片解码失败？ 图片尺寸540x960

**Comment by panpf** [comment]
偶尔的还是只要是这张图片一定会出问题

**Comment by 501956430** [comment]
@panpf 有时候会出现

**Comment by panpf** [comment]
应该是图片服务器的问题，有时候下载到的可能不是一张图片就解析不了
