### ISSUE TITLE
demo 中加载图片显示的loading圆圈加载百分比怎么配置？

### ISSUE THREAD

**Issue by 501956430** [panpf/sketch#78]

**Comment by panpf** [comment]
什么意思？没看明白

**Comment by 501956430** [comment]
@panpf 这是sketch app中的 ,指的这个
![image](https://user-images.githubusercontent.com/20204491/42267047-90af3508-7faa-11e8-96b2-52b75ffbfe90.png)

**Comment by panpf** [comment]
请参考这篇 wiki https://github.com/panpf/sketch/blob/master/docs/wiki/listener.md

**Comment by 501956430** [comment]
@panpf  通过监听setDownloadProgressListener。能获得下载的当前进度，通过计算得出百分比。
现在的问题是如何将计算得出的百分比设置并显示。并未找到api中设置进度值的方法，请指导一下，谢谢。

**Comment by panpf** [comment]
显示进度需要你自己做 sketch 库没有提供这样的功能
