### ISSUE TITLE
缩放

### ISSUE THREAD

**Issue by jasonLYF** [panpf/sketch#79]
我想达到一种效果：
查看大图时 进入页面后直接展示到是经过缩放后可以充满宽或高，双击又可以再放大一些。
这个要怎么实现？ 
现在到情况时：如果我开阅读模式，一进去时可以充满宽或高到，但是双击后就变成可以看到全图到缩小样式了。

**Comment by jasonLYF** [comment]
类似微博查看图片到效果

**Comment by panpf** [comment]
2.6.2 版本提供了自定义缩放比例功能，你可以自定义实现此需求，详情请查看更新日志
