### ISSUE TITLE
Get Width and height of the image (Dimension) 

### ISSUE THREAD

**Issue by varoon** [panpf/sketch#80]
Hello, 
I need to display the "original" width and height of the rendered image. 
Does sketch have any pre-defined function to get ? 

Example: 800 x 1020 (width x height)

**Comment by panpf** [comment]
Proactively set a maxSize larger than 800x1020

**Comment by varoon** [comment]
Hello, Thanks for the reply. 
I think you have misunderstood. let me explain,

We have a something like "image viewer" in the app.  User can view all images in the app. 
There are different image size in gallery. the rendering is great! thanks to Sketck!

we have an option to display "image info" in that image name, path, dimension and file size are displayed on it. 

Here comes the issue, the dimension (width and height) of the Original image file is needed. 
Right now we get Rendered preview dimension which is actually wrong info.

Example:
Rendered image preview: 800x1020
Actual image dimension : 1670x2045 

we need to get the "actual dimension" of the image file and display on info page. 
Need help to get this Actual image dimension.

**Comment by panpf** [comment]
Now that I understand your requirements, all the drawables returned by Sketch implement the SketchDrawable interface. The interface has getOriginWidth() and getOriginHeight() methods to get the original size. The code example is as follows:
```java
SketchImageView imageView = ...;
imageView.setDisplayListener(new DisplayListener(){
         @Override
         Public void onStarted() {
            
         }

         @Override
         Public void onCompleted(@NonNull Drawable drawable, @NonNull ImageFrom imageFrom, @NonNull ImageAttrs imageAttrs) {
             SketchDrawable sketchDrawable = (SketchDrawable) drawable;
                 sketchDrawable.getOriginWidth();
                 sketchDrawable.getOriginHeight();
         }

         @Override
         Public void onError(@NonNull ErrorCause errorCause) {
            
         }

         @Override
         Public void onCanceled(@NonNull CancelCause cancelCause) {
            
         }
});
```
