### ISSUE TITLE
如何单击后预览本地图片全屏效果？

### ISSUE THREAD

**Issue by geekxingyun** [panpf/sketch#82]
求指教：

如果加载本地图片，开启缩放后如何让他全屏显示该图片，类似微信那种？

**Comment by panpf** [comment]
请详细说明需求，另外你可以先看看 demo 里有没有你说的效果

**Comment by geekxingyun** [comment]
需求就是用您这个控件加载一个本地图片，点击后就全屏预览图片，类似微信相册中的图片，现在只是点击扩大了几倍。

**Comment by panpf** [comment]
进 QQ 群详细沟通

**Comment by geekxingyun** [comment]
问题已经解决，这个需求其实是想传入一个图片路径，然后提供图片全屏预览功能的Activity.
`Intent intent=new Intent(mContext, PreviewPhotoActivity.class);
 intent.putExtra("previewPhotoPath",uploadFileList.get(position));
 mContext.startActivity(intent);`
类似上面这种调用方法，而不需要去xml中定义ImageView 视图
`    <me.panpf.sketch.SketchImageView
        android:id="@+id/common_preview_image_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:scaleType="centerInside"
    />
`
由于在下使用的是横向的RecycleView 显示一组图片，当点击一个Item时候想让该图片全屏显示。
但是由于RecycleView 的高度是有限制的，所以直接在RecycleViewAdapter 中的xml里面设置SketchImageView是没有任何效果的。

一直想偷懒，最后还是没办法自己写了一个PreviewPhotoActivity.java 类来做预览。
临时解决方案：
定义一个新的activity_previewphoto.xml：
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">


    <me.panpf.sketch.SketchImageView
        android:id="@+id/common_preview_image_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:scaleType="centerInside"
    />

</LinearLayout>`

创建一个PreviewPhotoActivity.java 

`  String previewFilePath= null;
        try {
            previewFilePath = getIntent().getStringExtra("previewPhotoPath");
        } catch (Exception e) {
            SmartLogUtils.debugInformation(e.toString(),true);
        }

        if(previewFilePath!=null&& !previewFilePath.isEmpty()){
            commonPreviewImageView.displayImage(previewFilePath);
            commonPreviewImageView.setZoomEnabled(true);
        }`
