### ISSUE TITLE
加载大图时，缩放过程中，中间会出现一条黑线

### ISSUE THREAD

**Issue by ALguojian** [panpf/sketch#83]
![wechatimg1](https://user-images.githubusercontent.com/29728638/44029604-76f04850-9f30-11e8-8fec-9209da3e9b4b.jpeg)

**Comment by ALguojian** [comment]
老铁有空修改一下

**Comment by panpf** [comment]
已经复现问题，正在修改

**Comment by ALguojian** [comment]
静候佳音

**Comment by ALguojian** [comment]
老铁，怎么样了，是否已经提上日程

**Comment by panpf** [comment]
已在 2.6.2 beta1 版本修复，欢迎试用
