### ISSUE TITLE
缩放有叠影

### ISSUE THREAD

**Issue by geekxingyun** [panpf/sketch#84]
当点击进入预览模式后，如果按住图片进行快速缩放会有叠影

**Comment by panpf** [comment]
有图才有真相

**Comment by geekxingyun** [comment]
真相在图中，快速缩放就会出现叠影

![2](https://user-images.githubusercontent.com/23736314/44207887-513bbf00-a191-11e8-9a55-4ba7d4e7a09c.png)

**Comment by geekxingyun** [comment]
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">


    <me.panpf.sketch.SketchImageView
        android:id="@+id/common_preview_image_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:scaleType="centerInside"
    />

</FrameLayout>

` 
@BindView(R.id.common_preview_image_view)

  SketchImageView commonPreviewImageView;

commonPreviewImageView.displayResourceImage(R.drawable.default_device_struct);

commonPreviewImageView.setZoomEnabled(true);
`
很是奇怪
