### ISSUE TITLE
ImageView.getZoomer().setReadMode(true)后出现的问题

### ISSUE THREAD

**Issue by liuxiangteng** [panpf/sketch#85]
设置阅读模式以后    在浏览 宽特别大高特别小的图片 的时候  会出现高填满屏幕的情况  
这样的体验是不是不太好   应该还是宽填满屏幕

**Comment by panpf** [comment]
单独的 zoomimage （ https://github.com/panpf/zoomimage ）库来了，支持 compose 和 view，两个版本逻辑和体验完全一致

新的 zoomimage 库在 sketch-zoom 的基础上完全重构，用户体验全面提升，除修复了一些 bug 之外还新支持了子采样碎片的动画和清晰度渐变以及支持 glide、picasso、coil、等图片加载器

目前已经到了公开测试的 beta 阶段，欢迎到 [release](https://github.com/panpf/zoomimage/releases) 页面下载 APK 体验效果
