### ISSUE TITLE
请问图片放大的时候上下左右的滚动进度条如何隐藏？

### ISSUE THREAD

**Issue by LiaoYuqiangzz** [panpf/sketch#89]
图片放大的时候，图片的下面和右边会出现滚动条，能否隐藏这个滚动条的呢？

**Comment by panpf** [comment]
不能隐藏，请问滚动条有什么问题吗？为什么要隐藏？

**Comment by panpf** [comment]
全新 3.0 版本已经发布 alpha 版，欢迎体验。新版本可以隐藏滚动条了

**Comment by panpf** [comment]
单独的 zoomimage （ https://github.com/panpf/zoomimage ）库来了，支持 compose 和 view，两个版本逻辑和体验完全一致

新的 zoomimage 库在 sketch-zoom 的基础上完全重构，用户体验全面提升，除修复了一些 bug 之外还新支持了子采样碎片的动画和清晰度渐变以及支持 glide、picasso、coil、等图片加载器

目前已经到了公开测试的 beta 阶段，欢迎到 [release](https://github.com/panpf/zoomimage/releases) 页面下载 APK 体验效果
