### ISSUE TITLE
圆角

### ISSUE THREAD

**Issue by zzhdroid1990** [panpf/sketch#92]
我使用
![image](https://user-images.githubusercontent.com/3402010/50392839-c2692f80-078c-11e9-9253-5ca1c0bda169.png)
该方法，有的时候图片设置为 center_crop 属性，圆角会被覆盖掉，这问题该怎么处理

**Comment by panpf** [comment]
这是因为你的图片较小，且跟 ImageView 的尺寸比例不一致，放大并且裁剪后圆角给裁掉了，你可以使用 ImageShaper 并配合 ShapeSize 实现你要的效果，详情请参考 demo

**Comment by zzhdroid1990** [comment]
👌，明白了，我再研究一下

**Comment by zzhdroid1990** [comment]
> 这是因为你的图片较小，且跟 ImageView 的尺寸比例不一致，放大并且裁剪后圆角给裁掉了，你可以使用 ImageShaper 并配合 ShapeSize 实现你要的效果，详情请参考 demo

👌，明白了，我再研究一下
